
import React, { useState } from 'react';
import { User, UserRole } from '../types.ts';
import { ClinicalAPI } from '../services/apiService.ts';

interface LoginProps {
  onLogin: (user: User) => void;
}

const Login: React.FC<LoginProps> = ({ onLogin }) => {
  const [isRegister, setIsRegister] = useState(false);
  const [step, setStep] = useState(1);
  const [role, setRole] = useState<UserRole>(UserRole.PATIENT);
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const [password, setPassword] = useState('');
  const [age, setAge] = useState('');
  const [bloodType, setBloodType] = useState('');
  const [genotype, setGenotype] = useState('');
  const [address, setAddress] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const isCloud = ClinicalAPI.isConfigured();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      if (isRegister) {
        if (role === UserRole.PATIENT && step === 1) {
          setStep(2);
          setLoading(false);
          return;
        }

        const newUser: User = {
          id: '', // Generated by API
          name,
          email: email.toLowerCase(),
          role,
          isApproved: role !== UserRole.CONSULTANT, // Consultants need manual verification
          ...(role === UserRole.PATIENT ? { 
            age: parseInt(age), 
            bloodType, 
            genotype, 
            address 
          } : {})
        };

        const registeredUser = await ClinicalAPI.signUp(email, password, newUser);
        onLogin(registeredUser);
      } else {
        const loggedUser = await ClinicalAPI.signIn(email, password);
        onLogin(loggedUser);
      }
    } catch (err: any) {
      setError(err.message || "Authentication failed. Please check your credentials.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-[calc(100vh-128px)] flex items-center justify-center bg-slate-50 p-4">
      <div className="bg-white w-full max-w-md rounded-[3rem] shadow-2xl border border-slate-100 overflow-hidden relative">
        <div className="p-10 md:p-12 relative z-10">
          <div className="text-center mb-10">
            <div className="w-16 h-16 bg-emerald-600 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-xl shadow-emerald-200">
              <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" /></svg>
            </div>
            <h2 className="text-3xl font-black text-slate-900 tracking-tight">
              {isRegister ? 'Clinical Intake' : 'Portal Access'}
            </h2>
            <div className="mt-2 flex flex-col items-center">
              <p className="text-slate-500 font-medium text-sm">Byinks Health Infrastructure</p>
              <span className={`mt-2 px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest ${isCloud ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' : 'bg-slate-100 text-slate-400 border border-slate-200'}`}>
                {isCloud ? 'Cloud Mode Active' : 'Local Sandbox Mode'}
              </span>
            </div>
          </div>

          {error && (
            <div className="mb-6 p-4 bg-red-50 border border-red-100 rounded-2xl text-[10px] font-black text-red-700 uppercase tracking-widest leading-relaxed flex items-start space-x-3">
              <svg className="w-5 h-5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-6">
            {step === 1 ? (
              <div className="space-y-5">
                {isRegister && (
                  <div className="grid grid-cols-3 gap-2 p-1 bg-slate-100 rounded-2xl mb-4">
                    <button type="button" onClick={() => setRole(UserRole.PATIENT)} className={`py-2 text-[8px] font-black rounded-xl transition uppercase tracking-widest ${role === UserRole.PATIENT ? 'bg-white shadow text-emerald-600' : 'text-slate-400'}`}>Patient</button>
                    <button type="button" onClick={() => setRole(UserRole.CONSULTANT)} className={`py-2 text-[8px] font-black rounded-xl transition uppercase tracking-widest ${role === UserRole.CONSULTANT ? 'bg-white shadow text-emerald-600' : 'text-slate-400'}`}>Doctor</button>
                    <button type="button" onClick={() => setRole(UserRole.ADMIN)} className={`py-2 text-[8px] font-black rounded-xl transition uppercase tracking-widest ${role === UserRole.ADMIN ? 'bg-slate-900 shadow text-white' : 'text-slate-400'}`}>Admin</button>
                  </div>
                )}
                {isRegister && (
                  <input required placeholder="Legal Name" value={name} onChange={e => setName(e.target.value)} className="w-full px-6 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none font-medium" />
                )}
                <input required type="email" placeholder="Email Identifier" value={email} onChange={e => setEmail(e.target.value)} className="w-full px-6 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none font-medium" />
                <input required type="password" placeholder="Portal Password" value={password} onChange={e => setPassword(e.target.value)} className="w-full px-6 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none font-medium" />
              </div>
            ) : (
              <div className="space-y-5 animate-in slide-in-from-right-4">
                 <div className="grid grid-cols-2 gap-4">
                   <input required type="number" placeholder="Age" value={age} onChange={e => setAge(e.target.value)} className="w-full px-5 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none font-medium" />
                   <input required placeholder="Blood Group" value={bloodType} onChange={e => setBloodType(e.target.value)} className="w-full px-5 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none font-medium" />
                 </div>
                 <input required placeholder="Genotype (e.g., AA)" value={genotype} onChange={e => setGenotype(e.target.value)} className="w-full px-5 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none font-medium" />
                 <textarea required placeholder="Residential Address" value={address} onChange={e => setAddress(e.target.value)} className="w-full px-5 py-4 bg-slate-50 border border-slate-200 rounded-2xl outline-none h-24 font-medium" />
              </div>
            )}

            <button 
              type="submit" 
              disabled={loading}
              className="w-full py-5 bg-emerald-600 text-white rounded-[1.5rem] font-black text-xs uppercase tracking-widest hover:bg-emerald-700 transition shadow-xl shadow-emerald-200 disabled:opacity-50"
            >
              {loading ? 'Initializing...' : isRegister && step === 1 && role === UserRole.PATIENT ? 'Next: Medical Profile' : isRegister ? 'Initialize Identity' : 'Secure Sign In'}
            </button>
          </form>

          <div className="mt-10 pt-8 border-t border-slate-100 text-center">
            <button onClick={() => { setIsRegister(!isRegister); setStep(1); setError(''); }} className="text-emerald-600 font-black text-[10px] uppercase tracking-widest hover:underline">
              {isRegister ? 'Return to Authenticator' : 'Provision a New Clinical Identity'}
            </button>
          </div>
        </div>
        <div className="absolute top-0 left-0 w-full h-1.5 bg-gradient-to-r from-emerald-500 via-teal-500 to-emerald-500"></div>
      </div>
    </div>
  );
};

export default Login;
